### ISSUE TITLE
SSL Cert expired? (NET::ERR_CERT_DATE_INVALID)

### ISSUE THREAD

**Issue by szulcmaciej** [konradbartecki/Podatki.wtf.OpenSource#48]
When I open podatki.wtf (in Chrome, MacOS), I see this:
![image](https://github.com/konradbartecki/Podatki.wtf.OpenSource/assets/24300499/889df69c-3ca5-4878-9961-5689c2e5228e)

**Comment by kipelovets** [comment]
Same here, the certificate is definitely expired. Unfortunately this makes the site inaccessible from Chrome

<img width="599" alt="Screenshot 2024-02-27 at 17 32 53" src="https://github.com/konradbartecki/Podatki.wtf.OpenSource/assets/204543/fffb8197-88a9-4b7a-bc31-99df89429f27">

**Comment by konradbartecki** [comment]
Sorry for that, it is now fixed, thanks for letting me know!
